### ISSUE TITLE
SAF android 10 permissions

### ISSUE THREAD

**Issue by theoklink** [Adonai/jaudiotagger#4]
With the permission restrictions under android 10 the older libraries no longer work
As this was a recent update I was hoping it had implemented the Storage Access Framework but I found the same error as with for instance jid3
org.jaudiotagger.audio.exceptions.NoReadPermissionsException: Unable to read file do not have permission to read: /storage/AD7D-190E/Music/Who/Tommy/Tommy Disc 2/01 Do You Think It's Alright-.mp3
MP3File musicFile = (MP3File) AudioFileIO.read(SourceFile); fails
Can you shed light on this?

**Comment by Kaned1as** [comment]
This library won't be updated to work with SAF, it doesn't have any Android dependencies and I don't have any plans for that. If you want this done, please send PR.

**Comment by Kaned1as** [comment]
If you want to use this library in some SAF-aware application, take a look at how it's done in [Tag Editor](https://github.com/vanilla-music/vanilla-music-tag-editor)
